"""
weekly_paracha_pages.py
-----------------------
Rendering side of the weekly "Rendez-vous paracha" (see weekly_paracha.py for
the selection / summary side). Stdlib only, on purpose: generate_channel_pages.py
imports `sitemap_entries()` from here, and the generator test-suite runs with
pytest alone (no requests / anthropic).

Inputs are the per-week data files `paracha/<week>.json` written by
weekly_paracha.py. Outputs, all SOURCE files committed by the weekly workflow
(never regenerated by the hourly pipeline nor by deploy-site):

  paracha-de-la-semaine.html   rolling page = the latest week + archive list
  paracha/<week>.html          one archive page per week (self-canonical)
  paracha-de-la-semaine.xml    RSS 2.0 feed, one item per week (newsletters,
                               aggregators, RSS-to-Telegram bridges...)

A week file is the single source of truth of its page: rendering is a pure
function of the JSON files on disk, so re-rendering is idempotent.
"""
from __future__ import annotations

import html as _html
import json
from datetime import datetime, timedelta, timezone
from email.utils import format_datetime
from pathlib import Path

BASE_URL = "https://thetorahpodcast.net"
DATA_DIR = Path("paracha")
ROLLING_PAGE = "paracha-de-la-semaine.html"
FEED_FILE = "paracha-de-la-semaine.xml"
FEED_MAX_ITEMS = 30
ARCHIVE_MAX_LINKS = 60

MONTHS_FR = [
    "janvier", "février", "mars", "avril", "mai", "juin",
    "juillet", "août", "septembre", "octobre", "novembre", "décembre",
]

# Same brand entity as generate_channel_pages.SITE_PUBLISHER (the @id matches
# the Organization declared on index.html). Kept literal here to keep this
# module importable by the generator without a circular import.
SITE_PUBLISHER = {
    "@type": "Organization",
    "@id": f"{BASE_URL}/#organization",
    "name": "The Torah Podcast",
    "url": f"{BASE_URL}/",
}


def esc(s) -> str:
    return _html.escape("" if s is None else str(s), quote=True)


def fmt_date_fr(iso: str) -> str:
    try:
        d = datetime.fromisoformat(str(iso)[:10])
    except ValueError:
        return str(iso)[:10]
    return f"{d.day} {MONTHS_FR[d.month - 1]} {d.year}"


def fmt_dur(secs) -> str:
    try:
        secs = int(secs or 0)
    except (TypeError, ValueError):
        return ""
    if secs <= 0:
        return ""
    h, rem = divmod(secs, 3600)
    m = rem // 60
    return f"{h} h {m:02d}" if h else f"{m} min"


def week_url(week: str) -> str:
    return f"{BASE_URL}/paracha/{week}.html"


# --------------------------------------------------------------------------
# Data files
# --------------------------------------------------------------------------

def load_weeks(data_dir: Path = DATA_DIR) -> list[dict]:
    """Every week data file, newest Shabbat first. Unreadable files are skipped
    loudly (a corrupt file must not take the whole feed down)."""
    weeks = []
    if not data_dir.is_dir():
        return weeks
    for f in sorted(data_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            print(f"WARNING: skipping unreadable {f}: {exc}")
            continue
        if data.get("week") and data.get("shabbat") and data.get("courses") is not None:
            weeks.append(data)
    weeks.sort(key=lambda w: (w["shabbat"], w["week"]), reverse=True)
    return weeks


def weekly_page_link(reading: dict, ref_date=None, data_dir: Path = DATA_DIR) -> str | None:
    """URL of the rolling page when its latest week covers `reading` for the
    Shabbat on or after `ref_date` (default: today UTC), else None. Used by the
    Friday post of social_post.py, which keeps its paracha.html link otherwise
    (e.g. the Thursday run was skipped by GitHub's cron)."""
    ref = ref_date or datetime.now(timezone.utc).date()
    shabbat = (ref + timedelta(days=(5 - ref.weekday()) % 7)).isoformat()
    weeks = load_weeks(data_dir)
    if weeks and weeks[0]["shabbat"] == shabbat and weeks[0]["reading"].get("slugs") == reading.get("slugs"):
        return f"{BASE_URL}/{ROLLING_PAGE}"
    return None


# --------------------------------------------------------------------------
# Sitemap (called by generate_channel_pages.update_sitemap)
# --------------------------------------------------------------------------

def sitemap_entries(today: str, data_dir: Path = DATA_DIR) -> str:
    """<url> blocks for the rolling page + every archive page, or "".

    Deterministic from the files on disk: the rolling page is stamped with the
    build day (like the other static pages: a tolerated <lastmod> difference
    for site_compare), archives with the day they were generated."""
    weeks = load_weeks(data_dir)
    if not weeks or not Path(ROLLING_PAGE).is_file():
        return ""
    blocks = [
        "  <url>\n"
        f"    <loc>{BASE_URL}/{ROLLING_PAGE}</loc>\n"
        f"    <lastmod>{today}</lastmod>\n"
        "    <changefreq>weekly</changefreq>\n"
        "    <priority>0.8</priority>\n"
        "  </url>"
    ]
    for w in weeks:
        if not (data_dir / f"{w['week']}.html").is_file():
            continue
        blocks.append(
            "  <url>\n"
            f"    <loc>{week_url(w['week'])}</loc>\n"
            f"    <lastmod>{str(w.get('generated_at') or w['shabbat'])[:10]}</lastmod>\n"
            "    <changefreq>yearly</changefreq>\n"
            "    <priority>0.6</priority>\n"
            "  </url>"
        )
    return "\n".join(blocks) + "\n"


# --------------------------------------------------------------------------
# HTML
# --------------------------------------------------------------------------

CSS = """\
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; background: #f5f5f0; color: #222; line-height: 1.5; padding-bottom: 96px; }
    header { background: #1a1a2e; color: #fff; padding: 28px 20px; text-align: center; }
    header h1 { font-size: 2rem; margin-bottom: 6px; }
    header p { color: #aab; font-size: .95rem; margin-bottom: 14px; }
    .header-nav { display: flex; justify-content: center; flex-wrap: wrap; gap: 6px; padding: 0 16px 20px; }
    .header-nav a { color: rgba(255,255,255,.65); text-decoration: none; font-size: .8rem; padding: 5px 14px; border-radius: 20px; border: 1px solid rgba(255,255,255,.2); }
    .header-nav a:hover { color: #fff; border-color: rgba(255,255,255,.5); background: rgba(255,255,255,.1); }
    .header-nav a.active { color: #1a1a2e; background: #fff; border-color: #fff; font-weight: 600; }
    .nav-dropdown { position: relative; display: inline-flex; }
    .nav-dd-link { border-radius: 20px 0 0 20px !important; padding-right: 4px !important; }
    .nav-dd-caret { color: rgba(255,255,255,.65); font-size: .8rem; padding: 5px 10px 5px 6px; border-radius: 0 20px 20px 0; border: 1px solid rgba(255,255,255,.2); border-left: none; background: none; cursor: pointer; }
    .nav-submenu { display: none; position: absolute; top: calc(100% + 8px); left: 50%; transform: translateX(-50%); background: #252545; border: 1px solid rgba(255,255,255,.15); border-radius: 14px; padding: 10px; z-index: 50; flex-wrap: wrap; gap: 6px; min-width: 260px; }
    .nav-dropdown.open .nav-submenu { display: flex; }
    .nav-submenu a { white-space: nowrap; }
    .lang-switch { display: inline-flex; gap: 2px; margin: 6px auto 14px; padding: 2px; border: 1px solid rgba(255,255,255,.2); border-radius: 20px; background: rgba(255,255,255,.05); }
    .lang-opt { color: rgba(255,255,255,.6); font-size: .75rem; font-weight: 600; padding: 4px 11px; border-radius: 16px; border: none; background: none; cursor: pointer; }
    .lang-opt.active { background: #e87722; color: #fff; }
    .breadcrumb { max-width: 860px; margin: 14px auto 0; padding: 0 16px; font-size: .8rem; color: #777; }
    .breadcrumb ol { list-style: none; display: flex; flex-wrap: wrap; gap: 6px; }
    .breadcrumb li + li::before { content: "\\203A"; margin-inline-end: 6px; color: #aaa; }
    .breadcrumb a { color: #555; }
    main { max-width: 860px; margin: 0 auto; padding: 18px 16px 40px; }
    .wk-banner { background: #1a1a2e; color: #fff; border-radius: 14px; padding: 20px 24px; margin-bottom: 18px; }
    .wk-label { font-size: .7rem; text-transform: uppercase; letter-spacing: .08em; color: #99a; margin-bottom: 4px; }
    .wk-name { font-size: 1.5rem; font-weight: 700; }
    .wk-he { font-size: 1.15rem; color: #cce; direction: rtl; unicode-bidi: isolate; }
    .wk-date { font-size: .85rem; color: #aab; margin-top: 6px; }
    .wk-summary { background: #fff; border: 1px solid #e4e4dc; border-radius: 12px; padding: 16px 18px; margin-bottom: 8px; }
    .wk-summary p { margin-bottom: 6px; }
    .wk-summary p:last-child { margin-bottom: 0; }
    .wk-ai-note { font-size: .72rem; color: #888; margin: 0 4px 20px; }
    .wk-list { display: flex; flex-direction: column; gap: 10px; }
    .wk-course { display: flex; gap: 12px; background: #fff; border: 1px solid #e4e4dc; border-radius: 12px; padding: 10px; align-items: flex-start; }
    .wk-thumb { width: 120px; height: 68px; object-fit: cover; border-radius: 8px; flex-shrink: 0; background: #ddd; }
    .wk-body { flex: 1; min-width: 0; }
    .wk-title { font-weight: 600; color: #1a1a2e; text-decoration: none; display: block; overflow-wrap: anywhere; }
    .wk-title:hover { text-decoration: underline; }
    .wk-meta { font-size: .8rem; color: #666; margin-top: 2px; }
    .wk-meta a { color: #444; }
    .wk-badge { display: inline-block; font-size: .68rem; border: 1px solid #ccc; border-radius: 10px; padding: 0 7px; margin-inline-start: 4px; color: #555; }
    .wk-actions { margin-top: 6px; display: flex; gap: 8px; flex-wrap: wrap; }
    .wk-play { background: #e87722; color: #fff; border: none; border-radius: 16px; padding: 4px 14px; font-size: .8rem; font-weight: 600; cursor: pointer; }
    .wk-play:hover { background: #f2872f; }
    .wk-more { margin: 18px 0; font-size: .9rem; }
    .wk-more a { color: #1a1a2e; font-weight: 600; }
    .wk-archives { margin-top: 28px; }
    .wk-archives h2 { font-size: 1rem; margin-bottom: 8px; }
    .wk-archives ul { list-style: none; display: flex; flex-wrap: wrap; gap: 6px; }
    .wk-archives a { display: inline-block; font-size: .8rem; padding: 4px 12px; border: 1px solid #ddd; border-radius: 20px; background: #fff; color: #333; text-decoration: none; }
    .wk-archives a:hover { border-color: #1a1a2e; }
    .wk-rss { font-size: .8rem; margin-top: 18px; color: #666; }
    .wk-rss a { color: #e87722; }
    .site-footer { text-align: center; font-size: .8rem; color: #888; padding: 24px 16px; }
    .site-footer a { color: #666; }
    @media (max-width: 560px) { .wk-thumb { width: 88px; height: 50px; } .wk-name { font-size: 1.25rem; } }
"""

# Fixed UI strings (the summary itself is French only).
I18N = {
    "fr": {"nav_home": "Accueil", "nav_rabbis": "Rabbins", "nav_last_classes": "Derniers cours",
           "nav_limud": "Limud Yomi", "nav_daf_hayomi": "Daf Hayomi", "nav_hitat": "Hitat Yomi",
           "nav_hayomyom": "Hayom Yom", "nav_paracha": "Paracha", "nav_themes": "Thème",
           "subtitle": "Les cours de la semaine sur la paracha", "wk_label": "Paracha de la semaine",
           "wk_label_holiday": "Fête de la semaine", "listen": "Écouter", "transcript": "transcription",
           "more": "Tous les cours sur cette paracha", "archives": "Les semaines précédentes",
           "ai_note": "Résumé rédigé automatiquement à partir des titres, descriptions et transcriptions des cours sélectionnés.",
           "rss": "Recevoir la sélection chaque semaine : flux RSS", "back": "Paracha de la semaine"},
    "en": {"nav_home": "Home", "nav_rabbis": "Rabbis", "nav_last_classes": "Latest classes",
           "nav_limud": "Limud Yomi", "nav_daf_hayomi": "Daf Hayomi", "nav_hitat": "Hitat Yomi",
           "nav_hayomyom": "Hayom Yom", "nav_paracha": "Parasha", "nav_themes": "Topics",
           "subtitle": "This week's classes on the parasha", "wk_label": "Parasha of the week",
           "wk_label_holiday": "Festival of the week", "listen": "Listen", "transcript": "transcript",
           "more": "All the classes on this parasha", "archives": "Previous weeks",
           "ai_note": "Summary written automatically from the titles, descriptions and transcripts of the selected classes (in French).",
           "rss": "Get the selection every week: RSS feed", "back": "Parasha of the week"},
    "he": {"nav_home": "ראשי", "nav_rabbis": "הרבנים", "nav_last_classes": "שיעורים אחרונים",
           "nav_limud": "לימוד יומי", "nav_daf_hayomi": "דף היומי", "nav_hitat": 'חת"ת',
           "nav_hayomyom": "היום יום", "nav_paracha": "פרשה", "nav_themes": "נושא",
           "subtitle": "שיעורי השבוע על הפרשה", "wk_label": "פרשת השבוע",
           "wk_label_holiday": "חג השבוע", "listen": "האזן", "transcript": "תמלול",
           "more": "כל השיעורים על הפרשה", "archives": "שבועות קודמים",
           "ai_note": "הסיכום (בצרפתית) נכתב אוטומטית מתוך הכותרות, התיאורים והתמלולים של השיעורים שנבחרו.",
           "rss": "לקבלת המבחר בכל שבוע: RSS", "back": "פרשת השבוע"},
}


def _title(data: dict) -> str:
    return f"{data['reading']['label_fr']} — les cours de la semaine"


def _description(data: dict) -> str:
    summary = " ".join((data.get("summary") or "").split())
    base = summary or (f"Les meilleurs cours de Torah sur {data['reading']['label_fr']}, "
                       "sélectionnés chaque semaine.")
    return base if len(base) <= 158 else base[:155].rsplit(" ", 1)[0] + "…"


def _og_image(data: dict) -> str:
    for c in data.get("courses", []):
        if c.get("artwork"):
            return c["artwork"]
    for c in data.get("courses", []):
        if c.get("thumbnail"):
            return c["thumbnail"]
    return f"{BASE_URL}/favicon.png"


def _jsonld(data: dict, url: str, rolling: bool) -> str:
    levels = [("Accueil", f"{BASE_URL}/"), ("Cours par Paracha", f"{BASE_URL}/paracha.html"),
              ("Paracha de la semaine", f"{BASE_URL}/{ROLLING_PAGE}")]
    if not rolling:
        levels.append((data["reading"]["label_fr"], url))
    graph = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": _title(data),
        "description": _description(data),
        "url": url,
        "inLanguage": "fr",
        "datePublished": str(data.get("generated_at", ""))[:10],
        "isPartOf": {"@type": "WebSite", "name": "The Torah Podcast", "url": f"{BASE_URL}/"},
        "publisher": SITE_PUBLISHER,
        "breadcrumb": {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": i + 1, "name": n, "item": u}
                for i, (n, u) in enumerate(levels)
            ],
        },
        "mainEntity": {
            "@type": "ItemList",
            "numberOfItems": len(data.get("courses", [])),
            "itemListElement": [
                {"@type": "ListItem", "position": i + 1, "url": c["url"], "name": c["title"]}
                for i, c in enumerate(data.get("courses", []))
            ],
        },
    }
    # `</` can never end the JSON-LD <script> block.
    return json.dumps(graph, ensure_ascii=False, indent=2).replace("</", "<\\/")


def _summary_html(summary: str) -> str:
    lines = [ln.strip() for ln in (summary or "").splitlines() if ln.strip()]
    return "\n".join(f"      <p>{esc(ln)}</p>" for ln in lines)


def _course_html(c: dict, i: int) -> str:
    thumb = (f'<a href="{esc(c["url"])}"><img class="wk-thumb" src="{esc(c["thumbnail"])}" '
             f'alt="" loading="lazy" width="120" height="68"></a>') if c.get("thumbnail") else ""
    dur = fmt_dur(c.get("duration_secs"))
    badges = ""
    if c.get("lang") == "he":
        badges += '<span class="wk-badge" lang="he">עברית</span>'
    if c.get("has_transcript"):
        badges += '<span class="wk-badge" data-i18n="transcript">transcription</span>'
    play = (f'<button type="button" class="wk-play" data-i="{i}" data-i18n="listen">Écouter</button>'
            if c.get("audio_url") else "")
    title_dir = ' dir="rtl" lang="he"' if c.get("lang") == "he" else ""
    return (
        '    <article class="wk-course">\n'
        f'      {thumb}\n'
        '      <div class="wk-body">\n'
        f'        <a class="wk-title" href="{esc(c["url"])}"{title_dir}>{esc(c["title"])}</a>\n'
        f'        <div class="wk-meta"><a href="{esc(c["rav_url"])}">{esc(c["rav"])}</a>'
        f' · <time datetime="{esc(c["published"][:10])}">{fmt_date_fr(c["published"])}</time>'
        f'{" · " + dur if dur else ""}{badges}</div>\n'
        f'        <div class="wk-actions">{play}</div>\n'
        '      </div>\n'
        '    </article>'
    )


def _archives_html(weeks: list[dict], current: str) -> str:
    items = [w for w in weeks if w["week"] != current][:ARCHIVE_MAX_LINKS]
    if not items:
        return ""
    lis = "\n".join(
        f'      <li><a href="/paracha/{esc(w["week"])}.html">{esc(w["reading"]["label_fr"])} '
        f'<small>({fmt_date_fr(w["shabbat"])})</small></a></li>'
        for w in items
    )
    return (
        '  <section class="wk-archives" id="archives">\n'
        '    <h2 data-i18n="archives">Les semaines précédentes</h2>\n'
        f'    <ul>\n{lis}\n    </ul>\n'
        '  </section>\n'
    )


def render_page(data: dict, weeks: list[dict], rolling: bool) -> str:
    reading = data["reading"]
    url = f"{BASE_URL}/{ROLLING_PAGE}" if rolling else week_url(data["week"])
    title = _title(data)
    desc = _description(data)
    og_image = _og_image(data)
    courses = data.get("courses", [])
    label_key = "wk_label" if reading.get("kind") == "parasha" else "wk_label_holiday"
    more_url = reading.get("more_url") or f"{BASE_URL}/paracha.html"
    player_items = [
        {"id": c.get("video_id", ""), "title": c["title"], "channel": c["rav"],
         "art": c.get("thumbnail", ""), "src": c.get("audio_url", "")}
        for c in courses
    ]
    player_json = json.dumps(player_items, ensure_ascii=False).replace("</", "<\\/")
    i18n_json = json.dumps(I18N, ensure_ascii=False).replace("</", "<\\/")
    crumbs = [("/", "Accueil", "nav_home"), ("/paracha.html", "Cours par Paracha", ""),
              (f"/{ROLLING_PAGE}", "Paracha de la semaine", "back")]
    if not rolling:
        crumbs.append((url, reading["label_fr"], ""))
    crumb_items = []
    for i, (href, name, key) in enumerate(crumbs):
        attr = f' data-i18n="{key}"' if key else ""
        if i == len(crumbs) - 1:
            crumb_items.append(f'    <li><span aria-current="page"{attr}>{esc(name)}</span></li>')
        else:
            crumb_items.append(f'    <li><a href="{esc(href)}"{attr}>{esc(name)}</a></li>')
    courses_html = "\n".join(_course_html(c, i) for i, c in enumerate(courses))
    archives = _archives_html(weeks, data["week"]) if rolling else (
        f'  <p class="wk-more"><a href="/{ROLLING_PAGE}#archives" data-i18n="back">'
        'Paracha de la semaine</a> →</p>\n')
    robots = "index, follow"
    return f"""<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="manifest" href="/manifest.json">
  <link rel="icon" type="image/png" href="/favicon.png">
  <meta name="theme-color" content="#1a1a2e">
  <link rel="apple-touch-icon" href="/favicon.png">
  <title>{esc(title)} | The Torah Podcast</title>
  <meta name="description" content="{esc(desc)}">
  <meta name="robots" content="{robots}">
  <link rel="canonical" href="{esc(url)}">
  <link rel="alternate" type="application/rss+xml" title="The Torah Podcast — la paracha de la semaine" href="{BASE_URL}/{FEED_FILE}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{esc(url)}">
  <meta property="og:title" content="{esc(title)}">
  <meta property="og:description" content="{esc(desc)}">
  <meta property="og:image" content="{esc(og_image)}">
  <meta property="og:site_name" content="The Torah Podcast">
  <meta property="og:locale" content="fr_FR">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{esc(title)}">
  <meta name="twitter:description" content="{esc(desc)}">
  <meta name="twitter:image" content="{esc(og_image)}">
  <script type="application/ld+json">
{_jsonld(data, url, rolling)}
  </script>
  <link rel="preconnect" href="https://www.googletagmanager.com">
  <link rel="preconnect" href="https://pub-a5fae25ce5124edebe0bf7393f72823c.r2.dev">
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-7Z2QEN865Y"></script>
  <script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments);}}gtag('js',new Date());gtag('config','G-7Z2QEN865Y');</script>
  <style>
{CSS}  </style>
</head>
<body>

<header>
  <h1><a href="/" style="color:inherit;text-decoration:none">The Torah Podcast</a></h1>
  <p data-i18n="subtitle">Les cours de la semaine sur la paracha</p>
  <div class="header-stats" id="header-stats"></div>
  <nav class="header-nav">
    <a href="/" data-i18n="nav_home">Accueil</a>
    <div class="nav-dropdown" id="nav-dropdown">
      <a class="nav-dd-link" href="/rabbins.html" data-i18n="nav_rabbis">Rabbins</a><button class="nav-dd-caret" aria-label="Voir la liste">▾</button>
      <div class="nav-submenu" id="nav-rabbis-submenu"><a class="nav-submenu-all" href="/rabbins.html">Tous les rabbins →</a></div>
    </div>
    <a href="/derniers-cours.html" data-i18n="nav_last_classes">Derniers cours</a>
    <div class="nav-dropdown">
      <a class="nav-dd-link" href="/daf-hayomi.html" data-i18n="nav_limud">Limud Yomi</a><button class="nav-dd-caret" aria-label="Limud Yomi">▾</button>
      <div class="nav-submenu" style="min-width:170px;flex-direction:column;">
        <a href="/daf-hayomi.html" data-i18n="nav_daf_hayomi">Daf Hayomi</a>
        <a href="/hitat.html" data-i18n="nav_hitat">Hitat Yomi</a>
        <a href="/hayom-yom.html" data-i18n="nav_hayomyom">Hayom Yom</a>
        <a href="/hiloula.html">Hiloula</a>
      </div>
    </div>
    <a href="/paracha.html" class="active" data-i18n="nav_paracha">Paracha</a>
    <a href="/themes.html" data-i18n="nav_themes">Thème</a>
  </nav>
  <div class="lang-switch" role="group" aria-label="Language">
    <button type="button" class="lang-opt" data-lang="fr" onclick="setLang('fr')">FR</button>
    <button type="button" class="lang-opt" data-lang="en" onclick="setLang('en')">EN</button>
    <button type="button" class="lang-opt" data-lang="he" onclick="setLang('he')">עב</button>
  </div>
</header>

  <nav class="breadcrumb" aria-label="Fil d'Ariane">
  <ol>
{chr(10).join(crumb_items)}
  </ol>
  </nav>

<main>
  <section class="wk-banner">
    <div class="wk-label" data-i18n="{label_key}">{'Paracha de la semaine' if label_key == 'wk_label' else 'Fête de la semaine'}</div>
    <h2 class="wk-name">{esc(reading['label_fr'])}</h2>
    <div class="wk-he" lang="he" dir="rtl">{esc(reading.get('label_he', ''))}</div>
    <div class="wk-date">Chabbat du {fmt_date_fr(data['shabbat'])} · {len(courses)} cours · {len({c['rav'] for c in courses})} rabbins</div>
  </section>

  <section class="wk-summary" lang="fr" dir="ltr">
{_summary_html(data.get('summary', ''))}
  </section>
  <p class="wk-ai-note" data-i18n="ai_note">Résumé rédigé automatiquement à partir des titres, descriptions et transcriptions des cours sélectionnés.</p>

  <div class="wk-list">
{courses_html}
  </div>

  <p class="wk-more"><a href="{esc(more_url)}" data-i18n="more">Tous les cours sur cette paracha</a> →</p>
{archives}  <p class="wk-rss"><a href="/{FEED_FILE}" data-i18n="rss">Recevoir la sélection chaque semaine : flux RSS</a></p>
</main>

<script src="/js/utils.js"></script>
<script>
var WK_I18N = {i18n_json};
var WK_ITEMS = {player_json};
var lang = localStorage.getItem('lang') || 'fr';
if (!WK_I18N[lang]) lang = 'fr';
function t(k) {{ return (WK_I18N[lang] || {{}})[k] || WK_I18N.fr[k] || k; }}
function applyLang() {{
  document.querySelectorAll('.lang-opt').forEach(function (b) {{ b.classList.toggle('active', b.dataset.lang === lang); }});
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr';
  document.querySelectorAll('[data-i18n]').forEach(function (el) {{ el.textContent = t(el.dataset.i18n); }});
}}
function setLang(l) {{ if (l === lang) return; localStorage.setItem('lang', l); location.reload(); }}
applyLang();
document.addEventListener('click', function (ev) {{
  var btn = ev.target.closest ? ev.target.closest('.wk-play') : null;
  if (!btn) return;
  var it = WK_ITEMS[+btn.dataset.i];
  if (!it || !it.src) return;
  if (window.TTPPlayer) {{ window.TTPPlayer.load(it); }}
  else {{ window.open(it.src, '_blank', 'noopener'); }}
}});
document.querySelectorAll('.nav-dd-caret').forEach(function (b) {{
  b.addEventListener('click', function (e) {{ e.stopPropagation(); b.parentElement.classList.toggle('open'); }});
}});
</script>
<script>if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');</script>

<footer class="site-footer">
  <a href="/contact.html">Contactez-nous</a>
  &nbsp;·&nbsp;
  <a href="/cgv.html">Mentions légales</a>
  &nbsp;·&nbsp;
  <span>© {str(data['shabbat'])[:4]} The Torah Podcast</span>
</footer>
</body>
</html>
"""


# --------------------------------------------------------------------------
# RSS
# --------------------------------------------------------------------------

def _rfc822(iso: str) -> str:
    try:
        d = datetime.fromisoformat(str(iso).replace("Z", "+00:00"))
    except ValueError:
        d = datetime.fromisoformat(str(iso)[:10])
    if d.tzinfo is None:
        d = d.replace(tzinfo=timezone.utc)
    return format_datetime(d.astimezone(timezone.utc), usegmt=True)


def _item_html(w: dict) -> str:
    parts = [f"<p>{esc(ln.strip())}</p>" for ln in (w.get("summary") or "").splitlines() if ln.strip()]
    lis = "".join(
        f'<li><a href="{esc(c["url"])}">{esc(c["title"])}</a> — {esc(c["rav"])}</li>'
        for c in w.get("courses", [])
    )
    parts.append(f"<ul>{lis}</ul>")
    parts.append(f'<p><a href="{esc(week_url(w["week"]))}">Écouter la sélection sur The Torah Podcast</a></p>')
    return "".join(parts)


def render_feed(weeks: list[dict]) -> str:
    items = []
    for w in weeks[:FEED_MAX_ITEMS]:
        url = week_url(w["week"])
        items.append(
            "    <item>\n"
            f"      <title>{esc(w['reading']['label_fr'])} — les cours de la semaine</title>\n"
            f"      <link>{esc(url)}</link>\n"
            f'      <guid isPermaLink="true">{esc(url)}</guid>\n'
            f"      <pubDate>{_rfc822(w.get('generated_at') or w['shabbat'])}</pubDate>\n"
            f"      <description>{esc(_item_html(w))}</description>\n"
            "    </item>"
        )
    last = _rfc822(weeks[0].get("generated_at") or weeks[0]["shabbat"]) if weeks else ""
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n'
        "  <channel>\n"
        "    <title>The Torah Podcast — la paracha de la semaine</title>\n"
        f"    <link>{BASE_URL}/{ROLLING_PAGE}</link>\n"
        f'    <atom:link href="{BASE_URL}/{FEED_FILE}" rel="self" type="application/rss+xml"/>\n'
        "    <description>Chaque jeudi, une sélection des meilleurs cours de Torah sur la "
        "paracha (ou la fête) de la semaine, avec un court résumé.</description>\n"
        "    <language>fr</language>\n"
        f"    <lastBuildDate>{last}</lastBuildDate>\n"
        + ("\n".join(items) + "\n" if items else "")
        + "  </channel>\n</rss>\n"
    )


# --------------------------------------------------------------------------
# Write everything
# --------------------------------------------------------------------------

def write_all(data_dir: Path = DATA_DIR, root: Path = Path(".")) -> list[str]:
    """Render the rolling page, every archive page and the feed from the data
    files. Returns the repo-relative paths written."""
    weeks = load_weeks(data_dir)
    if not weeks:
        return []
    written = []
    for w in weeks:
        out = data_dir / f"{w['week']}.html"
        out.write_text(render_page(w, weeks, rolling=False), encoding="utf-8")
        written.append(out.as_posix())
    (root / ROLLING_PAGE).write_text(render_page(weeks[0], weeks, rolling=True), encoding="utf-8")
    (root / FEED_FILE).write_text(render_feed(weeks), encoding="utf-8")
    written += [ROLLING_PAGE, FEED_FILE]
    return written
